package com.texteditor.manager;

import com.texteditor.document.Document;
import com.texteditor.exception.DocumentNotFoundException;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.DisplayName;

import java.util.Set;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.CyclicBarrier;
import java.util.concurrent.atomic.AtomicInteger;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Comprehensive unit tests for DocumentManager.
 */
@DisplayName("DocumentManager Tests")
class DocumentManagerTest {

    private DocumentManager manager;

    @BeforeEach
    void setUp() {
        manager = new DocumentManager();
    }

    // ========== Constructor Tests ==========

    @Test
    @DisplayName("Constructor creates empty manager")
    void testConstructorCreatesEmpty() {
        assertEquals(0, manager.getDocumentCount());
        assertTrue(manager.getDocumentIds().isEmpty());
    }

    // ========== Create Document Tests ==========

    @Test
    @DisplayName("Create document with explicit ID")
    void testCreateDocumentWithExplicitId() {
        Document doc = manager.createDocument("test-doc", "Hello");

        assertNotNull(doc);
        assertEquals("test-doc", doc.getId());
        assertEquals("Hello", doc.getBuffer().toString());
        assertEquals(5, doc.length());
    }

    @Test
    @DisplayName("Create document with auto-generated ID")
    void testCreateDocumentWithAutoGeneratedId() {
        Document doc1 = manager.createDocument(null, "First");
        Document doc2 = manager.createDocument("", "Second");

        assertNotNull(doc1);
        assertNotNull(doc2);
        assertEquals("doc-1", doc1.getId());
        assertEquals("doc-2", doc2.getId());
    }

    @Test
    @DisplayName("Create document with empty content")
    void testCreateDocumentWithEmptyContent() {
        Document doc = manager.createDocument("empty-doc", "");

        assertEquals("empty-doc", doc.getId());
        assertEquals("", doc.getBuffer().toString());
        assertEquals(0, doc.length());
    }

    @Test
    @DisplayName("Create document with null content defaults to empty")
    void testCreateDocumentWithNullContent() {
        Document doc = manager.createDocument("doc-1", null);

        assertEquals("", doc.getBuffer().toString());
        assertEquals(0, doc.length());
    }

    @Test
    @DisplayName("Create document uses SimpleBuffer")
    void testCreateDocumentUsesSimpleBuffer() {
        Document doc = manager.createDocument("doc-1", "test");
        assertEquals("simple", doc.getBuffer().getType());
    }

    @Test
    @DisplayName("Create document rejects duplicate ID")
    void testCreateDocumentRejectsDuplicateId() {
        manager.createDocument("doc-1", "First");

        IllegalArgumentException exception = assertThrows(
            IllegalArgumentException.class,
            () -> manager.createDocument("doc-1", "Second")
        );

        assertTrue(exception.getMessage().contains("already exists"));
        assertTrue(exception.getMessage().contains("doc-1"));
    }

    @Test
    @DisplayName("Create multiple documents")
    void testCreateMultipleDocuments() {
        Document doc1 = manager.createDocument("doc-1", "First");
        Document doc2 = manager.createDocument("doc-2", "Second");
        Document doc3 = manager.createDocument("doc-3", "Third");

        assertEquals(3, manager.getDocumentCount());
        assertTrue(manager.hasDocument("doc-1"));
        assertTrue(manager.hasDocument("doc-2"));
        assertTrue(manager.hasDocument("doc-3"));
    }

    // ========== Get Document Tests ==========

    @Test
    @DisplayName("Get existing document")
    void testGetExistingDocument() throws DocumentNotFoundException {
        Document created = manager.createDocument("doc-1", "Hello");
        Document retrieved = manager.getDocument("doc-1");

        assertSame(created, retrieved); // Same object reference
        assertEquals("doc-1", retrieved.getId());
        assertEquals("Hello", retrieved.getBuffer().toString());
    }

    @Test
    @DisplayName("Get non-existent document throws exception")
    void testGetNonExistentDocument() {
        DocumentNotFoundException exception = assertThrows(
            DocumentNotFoundException.class,
            () -> manager.getDocument("non-existent")
        );

        assertEquals("non-existent", exception.getDocumentId());
        assertTrue(exception.getMessage().contains("non-existent"));
    }

    @Test
    @DisplayName("Get document with null ID throws exception")
    void testGetDocumentWithNullId() {
        assertThrows(
            IllegalArgumentException.class,
            () -> manager.getDocument(null)
        );
    }

    @Test
    @DisplayName("Get document immediately after creation")
    void testGetDocumentImmediatelyAfterCreation() throws DocumentNotFoundException {
        manager.createDocument("doc-1", "test");
        Document doc = manager.getDocument("doc-1");

        assertNotNull(doc);
        assertEquals("doc-1", doc.getId());
    }

    // ========== Close Document Tests ==========

    @Test
    @DisplayName("Close existing document")
    void testCloseExistingDocument() throws DocumentNotFoundException {
        manager.createDocument("doc-1", "test");
        assertEquals(1, manager.getDocumentCount());

        manager.closeDocument("doc-1");

        assertEquals(0, manager.getDocumentCount());
        assertFalse(manager.hasDocument("doc-1"));
    }

    @Test
    @DisplayName("Close non-existent document throws exception")
    void testCloseNonExistentDocument() {
        DocumentNotFoundException exception = assertThrows(
            DocumentNotFoundException.class,
            () -> manager.closeDocument("non-existent")
        );

        assertEquals("non-existent", exception.getDocumentId());
    }

    @Test
    @DisplayName("Close document with null ID throws exception")
    void testCloseDocumentWithNullId() {
        assertThrows(
            IllegalArgumentException.class,
            () -> manager.closeDocument(null)
        );
    }

    @Test
    @DisplayName("Cannot get document after closing")
    void testCannotGetDocumentAfterClosing() throws DocumentNotFoundException {
        manager.createDocument("doc-1", "test");
        manager.closeDocument("doc-1");

        assertThrows(
            DocumentNotFoundException.class,
            () -> manager.getDocument("doc-1")
        );
    }

    @Test
    @DisplayName("Can reuse ID after closing document")
    void testCanReuseIdAfterClosing() throws DocumentNotFoundException {
        manager.createDocument("doc-1", "First");
        manager.closeDocument("doc-1");

        // Should be able to create new document with same ID
        Document newDoc = manager.createDocument("doc-1", "Second");
        assertEquals("doc-1", newDoc.getId());
        assertEquals("Second", newDoc.getBuffer().toString());
    }

    @Test
    @DisplayName("Close multiple documents")
    void testCloseMultipleDocuments() throws DocumentNotFoundException {
        manager.createDocument("doc-1", "First");
        manager.createDocument("doc-2", "Second");
        manager.createDocument("doc-3", "Third");

        manager.closeDocument("doc-2");
        assertEquals(2, manager.getDocumentCount());
        assertTrue(manager.hasDocument("doc-1"));
        assertFalse(manager.hasDocument("doc-2"));
        assertTrue(manager.hasDocument("doc-3"));

        manager.closeDocument("doc-1");
        manager.closeDocument("doc-3");
        assertEquals(0, manager.getDocumentCount());
    }

    // ========== Has Document Tests ==========

    @Test
    @DisplayName("hasDocument returns true for existing document")
    void testHasDocumentReturnsTrue() {
        manager.createDocument("doc-1", "test");
        assertTrue(manager.hasDocument("doc-1"));
    }

    @Test
    @DisplayName("hasDocument returns false for non-existent document")
    void testHasDocumentReturnsFalse() {
        assertFalse(manager.hasDocument("non-existent"));
    }

    @Test
    @DisplayName("hasDocument returns false for null ID")
    void testHasDocumentWithNullId() {
        assertFalse(manager.hasDocument(null));
    }

    @Test
    @DisplayName("hasDocument returns false after closing")
    void testHasDocumentAfterClosing() throws DocumentNotFoundException {
        manager.createDocument("doc-1", "test");
        assertTrue(manager.hasDocument("doc-1"));

        manager.closeDocument("doc-1");
        assertFalse(manager.hasDocument("doc-1"));
    }

    // ========== Get Document IDs Tests ==========

    @Test
    @DisplayName("getDocumentIds returns empty set for empty manager")
    void testGetDocumentIdsEmpty() {
        Set<String> ids = manager.getDocumentIds();

        assertNotNull(ids);
        assertTrue(ids.isEmpty());
    }

    @Test
    @DisplayName("getDocumentIds returns all document IDs")
    void testGetDocumentIdsAll() {
        manager.createDocument("doc-1", "First");
        manager.createDocument("doc-2", "Second");
        manager.createDocument("doc-3", "Third");

        Set<String> ids = manager.getDocumentIds();

        assertEquals(3, ids.size());
        assertTrue(ids.contains("doc-1"));
        assertTrue(ids.contains("doc-2"));
        assertTrue(ids.contains("doc-3"));
    }

    @Test
    @DisplayName("getDocumentIds returns unmodifiable set")
    void testGetDocumentIdsUnmodifiable() {
        manager.createDocument("doc-1", "test");
        Set<String> ids = manager.getDocumentIds();

        assertThrows(
            UnsupportedOperationException.class,
            () -> ids.add("doc-2")
        );
    }

    @Test
    @DisplayName("getDocumentIds reflects document closure")
    void testGetDocumentIdsAfterClosure() throws DocumentNotFoundException {
        manager.createDocument("doc-1", "First");
        manager.createDocument("doc-2", "Second");

        manager.closeDocument("doc-1");

        Set<String> ids = manager.getDocumentIds();
        assertEquals(1, ids.size());
        assertFalse(ids.contains("doc-1"));
        assertTrue(ids.contains("doc-2"));
    }

    // ========== Get Document Count Tests ==========

    @Test
    @DisplayName("getDocumentCount returns 0 for empty manager")
    void testGetDocumentCountEmpty() {
        assertEquals(0, manager.getDocumentCount());
    }

    @Test
    @DisplayName("getDocumentCount returns correct count")
    void testGetDocumentCountCorrect() {
        assertEquals(0, manager.getDocumentCount());

        manager.createDocument("doc-1", "test");
        assertEquals(1, manager.getDocumentCount());

        manager.createDocument("doc-2", "test");
        assertEquals(2, manager.getDocumentCount());

        manager.createDocument("doc-3", "test");
        assertEquals(3, manager.getDocumentCount());
    }

    @Test
    @DisplayName("getDocumentCount decreases after closing")
    void testGetDocumentCountAfterClosing() throws DocumentNotFoundException {
        manager.createDocument("doc-1", "test");
        manager.createDocument("doc-2", "test");
        assertEquals(2, manager.getDocumentCount());

        manager.closeDocument("doc-1");
        assertEquals(1, manager.getDocumentCount());

        manager.closeDocument("doc-2");
        assertEquals(0, manager.getDocumentCount());
    }

    // ========== Auto-Generated ID Tests ==========

    @Test
    @DisplayName("Auto-generated IDs are sequential")
    void testAutoGeneratedIdsSequential() {
        Document doc1 = manager.createDocument(null, "First");
        Document doc2 = manager.createDocument(null, "Second");
        Document doc3 = manager.createDocument(null, "Third");

        assertEquals("doc-1", doc1.getId());
        assertEquals("doc-2", doc2.getId());
        assertEquals("doc-3", doc3.getId());
    }

    @Test
    @DisplayName("Auto-generated IDs continue after explicit IDs")
    void testAutoGeneratedIdsContinueAfterExplicit() {
        manager.createDocument(null, "Auto 1");  // doc-1
        manager.createDocument("custom", "Manual");
        Document doc = manager.createDocument(null, "Auto 2");  // doc-2

        assertEquals("doc-2", doc.getId());
    }

    @Test
    @DisplayName("Auto-generated IDs don't reuse after closing")
    void testAutoGeneratedIdsDontReuse() throws DocumentNotFoundException {
        Document doc1 = manager.createDocument(null, "First");  // doc-1
        assertEquals("doc-1", doc1.getId());

        manager.closeDocument("doc-1");

        Document doc2 = manager.createDocument(null, "Second");  // doc-2
        assertEquals("doc-2", doc2.getId());  // Not doc-1
    }

    // ========== Complex Scenario Tests ==========

    @Test
    @DisplayName("Complex document lifecycle")
    void testComplexDocumentLifecycle() throws DocumentNotFoundException {
        // Create documents
        Document doc1 = manager.createDocument("essay", "My Essay");
        Document doc2 = manager.createDocument(null, "Auto");

        assertEquals(2, manager.getDocumentCount());

        // Modify document
        doc1.insert(-1, " Content", true);
        assertEquals("My Essay Content", doc1.getBuffer().toString());

        // Retrieve and verify
        Document retrieved = manager.getDocument("essay");
        assertSame(doc1, retrieved);

        // Close one document
        manager.closeDocument("doc-1");
        assertEquals(1, manager.getDocumentCount());

        // Essay still accessible
        assertEquals("My Essay Content", manager.getDocument("essay").getBuffer().toString());

        // Close remaining
        manager.closeDocument("essay");
        assertEquals(0, manager.getDocumentCount());
    }

    @Test
    @DisplayName("Multiple documents with different content")
    void testMultipleDocumentsWithDifferentContent() throws DocumentNotFoundException {
        manager.createDocument("doc-1", "Content 1");
        manager.createDocument("doc-2", "Content 2");
        manager.createDocument("doc-3", "Content 3");

        assertEquals("Content 1", manager.getDocument("doc-1").getBuffer().toString());
        assertEquals("Content 2", manager.getDocument("doc-2").getBuffer().toString());
        assertEquals("Content 3", manager.getDocument("doc-3").getBuffer().toString());

        // Modify one doesn't affect others
        manager.getDocument("doc-2").insert(9, " Modified", false);  // Insert at end (after '2')
        assertEquals("Content 1", manager.getDocument("doc-1").getBuffer().toString());
        assertEquals("Content 2 Modified", manager.getDocument("doc-2").getBuffer().toString());
        assertEquals("Content 3", manager.getDocument("doc-3").getBuffer().toString());
    }

    // ========== Concurrency Tests ==========

    @Test
    @DisplayName("Concurrent document creation is thread-safe")
    void testConcurrentDocumentCreation() throws InterruptedException {
        int threadCount = 10;
        CountDownLatch latch = new CountDownLatch(threadCount);
        AtomicInteger successCount = new AtomicInteger(0);

        for (int i = 0; i < threadCount; i++) {
            final int threadNum = i;
            new Thread(() -> {
                try {
                    manager.createDocument("doc-" + threadNum, "Content " + threadNum);
                    successCount.incrementAndGet();
                } finally {
                    latch.countDown();
                }
            }).start();
        }

        latch.await();
        assertEquals(threadCount, successCount.get());
        assertEquals(threadCount, manager.getDocumentCount());
    }

    @Test
    @DisplayName("Concurrent auto-generated IDs are unique")
    void testConcurrentAutoGeneratedIdsUnique() throws InterruptedException {
        int threadCount = 20;
        CyclicBarrier barrier = new CyclicBarrier(threadCount);
        CountDownLatch latch = new CountDownLatch(threadCount);

        for (int i = 0; i < threadCount; i++) {
            new Thread(() -> {
                try {
                    barrier.await(); // All threads start together
                    manager.createDocument(null, "test");
                } catch (Exception e) {
                    // Ignore
                } finally {
                    latch.countDown();
                }
            }).start();
        }

        latch.await();
        assertEquals(threadCount, manager.getDocumentCount());

        // All IDs should be unique
        Set<String> ids = manager.getDocumentIds();
        assertEquals(threadCount, ids.size());
    }

    @Test
    @DisplayName("Concurrent read and write operations")
    void testConcurrentReadWrite() throws InterruptedException, DocumentNotFoundException {
        // Create initial document
        manager.createDocument("shared-doc", "Initial");

        int readerCount = 5;
        int writerCount = 5;
        CountDownLatch latch = new CountDownLatch(readerCount + writerCount);

        // Start readers
        for (int i = 0; i < readerCount; i++) {
            new Thread(() -> {
                try {
                    for (int j = 0; j < 100; j++) {
                        manager.getDocument("shared-doc");
                    }
                } catch (DocumentNotFoundException e) {
                    // Expected if document closed
                } finally {
                    latch.countDown();
                }
            }).start();
        }

        // Start writers (create/close other documents)
        for (int i = 0; i < writerCount; i++) {
            final int threadNum = i;
            new Thread(() -> {
                try {
                    for (int j = 0; j < 10; j++) {
                        String id = "temp-" + threadNum + "-" + j;
                        manager.createDocument(id, "temp");
                        manager.closeDocument(id);
                    }
                } catch (Exception e) {
                    // Ignore
                } finally {
                    latch.countDown();
                }
            }).start();
        }

        latch.await();

        // Shared document should still exist
        assertTrue(manager.hasDocument("shared-doc"));
    }
}
